<template>
  <div class="maintenance-report">
    <!-- Header -->
    <div class="report-header">
      <h1 class="company-name">{{ companyInfo.name }}</h1>
      <div class="company-info">
        <p>{{ companyInfo.address }}</p>
        <p>Phone: {{ companyInfo.phone }} | Email: {{ companyInfo.email }}</p>
      </div>
    </div>

    <v-divider class="my-6" />

    <!-- Report Title -->
    <div class="report-title">
      <h2>MAINTENANCE REPORT</h2>
      <p class="report-number">Report #{{ maintenance.id }}</p>
      <p class="report-date">Generated: {{ formatDate(new Date()) }}</p>
    </div>

    <v-divider class="my-6" />

    <!-- Vehicle Information -->
    <section class="report-section">
      <h3>VEHICLE INFORMATION</h3>
      <div class="section-content">
        <table class="info-table">
          <tr>
            <td><strong>Vehicle:</strong></td>
            <td>{{ maintenance.vehicleName }}</td>
          </tr>
          <tr>
            <td><strong>License Plate:</strong></td>
            <td>{{ maintenance.licensePlate }}</td>
          </tr>
          <tr v-if="maintenance.mileage">
            <td><strong>Mileage:</strong></td>
            <td>{{ maintenance.mileage.toLocaleString() }} miles</td>
          </tr>
        </table>
      </div>
    </section>

    <!-- Maintenance Details -->
    <section class="report-section">
      <h3>MAINTENANCE DETAILS</h3>
      <div class="section-content">
        <table class="info-table">
          <tr>
            <td><strong>Type:</strong></td>
            <td>{{ typeLabel }}</td>
          </tr>
          <tr>
            <td><strong>Status:</strong></td>
            <td>{{ maintenance.status.toUpperCase() }}</td>
          </tr>
          <tr>
            <td><strong>Priority:</strong></td>
            <td>{{ maintenance.priority.toUpperCase() }}</td>
          </tr>
          <tr>
            <td><strong>Scheduled Date:</strong></td>
            <td>{{ formatDate(maintenance.scheduledDate) }}</td>
          </tr>
          <tr v-if="maintenance.completedDate">
            <td><strong>Completed Date:</strong></td>
            <td>{{ formatDate(maintenance.completedDate) }}</td>
          </tr>
          <tr v-if="maintenance.performedBy">
            <td><strong>Service Provider:</strong></td>
            <td>{{ maintenance.performedBy }}</td>
          </tr>
        </table>
      </div>
    </section>

    <!-- Description -->
    <section class="report-section">
      <h3>DESCRIPTION</h3>
      <div class="section-content">
        <p>{{ maintenance.description }}</p>
      </div>
    </section>

    <!-- Notes -->
    <section v-if="maintenance.notes" class="report-section">
      <h3>NOTES</h3>
      <div class="section-content">
        <p>{{ maintenance.notes }}</p>
      </div>
    </section>

    <!-- Cost Information -->
    <section class="report-section">
      <h3>COST INFORMATION</h3>
      <div class="section-content">
        <table class="pricing-table">
          <tr>
            <td>{{ maintenance.status === 'completed' ? 'Actual Cost:' : 'Estimated Cost:' }}</td>
            <td class="amount">{{ formatCurrency(maintenance.cost) }}</td>
          </tr>
        </table>
      </div>
    </section>

    <!-- Footer -->
    <div class="report-footer">
      <p class="text-center">
        This is an official maintenance report generated by {{ companyInfo.name }}
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useCurrency } from '~/composables/useCurrency'

interface Props {
  maintenance: {
    id: string | number
    vehicleName: string
    licensePlate: string
    type: string
    status: string
    priority: string
    scheduledDate: string
    completedDate?: string
    description: string
    notes?: string
    cost: number
    mileage?: number
    performedBy?: string
  }
  typeLabel: string
  companyInfo?: {
    name: string
    address: string
    phone: string
    email: string
  }
}

const props = withDefaults(defineProps<Props>(), {
  companyInfo: () => ({
    name: 'Vehicle Rental Management',
    address: '123 Main Street, City, State 12345',
    phone: '(555) 123-4567',
    email: 'info@vrm.com'
  })
})

const { formatCurrency } = useCurrency()

const formatDate = (date: string | Date) => {
  const d = typeof date === 'string' ? new Date(date) : date
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}
</script>

<style scoped>
.maintenance-report {
  max-width: 8.5in;
  margin: 0 auto;
  padding: 0.75in;
  background: white;
  color: black;
  font-family: 'Times New Roman', serif;
  line-height: 1.6;
}

.report-header {
  text-align: center;
  margin-bottom: 2rem;
}

.company-name {
  font-size: 28px;
  font-weight: bold;
  margin-bottom: 0.5rem;
  color: #1a1a1a;
}

.company-info {
  font-size: 14px;
  color: #555;
}

.company-info p {
  margin: 0.25rem 0;
}

.report-title {
  text-align: center;
  margin: 2rem 0;
}

.report-title h2 {
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 0.5rem;
}

.report-number,
.report-date {
  font-size: 14px;
  color: #555;
  margin: 0.25rem 0;
}

.report-section {
  margin: 2rem 0;
  page-break-inside: avoid;
}

.report-section h3 {
  font-size: 18px;
  font-weight: bold;
  margin-bottom: 1rem;
  padding-bottom: 0.5rem;
  border-bottom: 2px solid #333;
}

.section-content {
  padding-left: 1rem;
}

.section-content p {
  margin: 0.5rem 0;
  color: #333;
  line-height: 1.6;
}

.info-table,
.pricing-table {
  width: 100%;
  border-collapse: collapse;
  margin: 1rem 0;
}

.info-table td,
.pricing-table td {
  padding: 0.5rem;
  border-bottom: 1px solid #ddd;
}

.info-table td:first-child {
  width: 40%;
}

.pricing-table td {
  padding: 0.75rem 0.5rem;
  font-size: 16px;
  font-weight: bold;
}

.pricing-table .amount {
  text-align: right;
  font-family: monospace;
}

.report-footer {
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 1px solid #ddd;
  font-size: 12px;
  color: #555;
}

/* Print styles */
@media print {
  .maintenance-report {
    padding: 0;
    max-width: none;
  }

  .report-section {
    page-break-inside: avoid;
  }

  .v-divider {
    display: none;
  }
}
</style>
